### ISSUE TITLE
Move firmware to FreeRTOS

### ISSUE THREAD

**Issue by janhieber** [janhieber/WaterCtrl#12]
Using FreeRTOS would be a big improvement to the current self written "scheduler".
**Pros:**
- Message queues and signalling between processes/threads
- Much easier programming because every thread has its own endless loop, no need for static vars and counters...
- Much cleaner design of codebase
- Much easier to change or enhance functionallity

I think point 2 is the biggest one and absolutely worth the switch to FreeRTOS.
As soon as I have a bit free time i will move this project over to FreeRTOS, but that can be summer...

**Comment by dropedout** [comment]
done
